# Generated by Django 4.0.6 on 2022-07-05 17:30

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=salesforce.fields.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='id',
            field=salesforce.fields.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
